#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/tests.v1.schema.json

test_format = 1.0

[default]
    # ------------
    # Tests to run
    # ------------

    preinstall = """
    sudo yunohost tools update apps
    sudo yunohost domain add dex.domain.tld
    sudo yunohost app install dex -f -a "domain=dex.domain.tld&path=/&oidc_name=&oidc_secret=&oidc_callback"

    sudo yunohost domain add minio.domain.tld
    sudo yunohost app install minio -f -a "domain=minio.domain.tld&init_main_permission=visitors&admin=package_checker&password=minio_password1234"

    echo "✅ End of preinstall"
    """

    preupgrade = """
    if [ "$FROM_COMMIT" == "5d1c5af" ]; then
        echo "🔧 Enabling celery..."
        sudo yunohost app config set $APP main.advanced.enable_celery -v yes
    fi
    echo "✅ End of preupgrade"
    """

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.dex = "dex"
    args.s3 = "minio"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.68d8460.name = "Upgrade from 3.4.0~ynh2"
