#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

ynh_redis_remove_db "$redis_db"
if use_celery; then
    ynh_redis_remove_db "$celery_redis_db"
fi

ynh_script_progression "Unregistering minio accesskey"
access_key=${app//_/-}
sudo -u minio "/var/www/minio/mc" admin accesskey remove minio/ "$access_key"

ynh_config_remove_logrotate

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi
if ynh_hide_warnings yunohost service status "$app-yprovider" >/dev/null; then
    yunohost service remove "$app-yprovider"
fi
if use_celery && ynh_hide_warnings yunohost service status "$app-celery" >/dev/null; then
    yunohost service remove "$app-celery"
fi

ynh_config_remove_systemd
ynh_config_remove_systemd "${app}-yprovider"
if use_celery; then
    ynh_config_remove_systemd "${app}-celery"
fi

ynh_config_remove_nginx

# Remove dex configuration
ynh_safe_rm "$dex_install_dir/config.yaml.d/$app"

if [ "${YNH_APP_PURGE:-0}" -eq 1 ]
then
    ynh_script_progression "Purging data from S3"
    # TODO: remove the bucket and access key
    ynh_print_warn "Purging data from S3 is not supported yet. If you would like to do that yourself, go to the MinIO admin panel or delete all the MinIO data"
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
