#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL NODEJS
#=================================================
ynh_script_progression "Reinstalling dependencies..."

ynh_nodejs_install

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

chown -R "$app:www-data" "$install_dir"

#=================================================
# RESTORE THE POSTGRESQL DATABASE
#=================================================
ynh_script_progression "Restoring the PostgreSQL database..."

ynh_psql_db_shell < ./db.sql

#=================================================
# RESTORE REDIS AND REGENERATE CONFIG
#=================================================
ynh_script_progression "Restoring Redis and $app's configuration files..."

redis_db=$(ynh_redis_get_free_db)
redis-cli -n "$redis_db" SET __YNH_PROVISIONED "$app"

celery_redis_db=$(ynh_redis_get_free_db)
redis-cli -n "$celery_redis_db" SET __YNH_PROVISIONED "$app"

ynh_app_setting_set --key=redis_db --value=$redis_db
ynh_app_setting_set --key=celery_redis_db --value=$celery_redis_db

ynh_config_add --template="env" --destination="$install_dir/.env"
chmod 400 "$install_dir/.env"
chown "$app:$app" "$install_dir/.env"

# YJS
ynh_config_add --template="env_yjs" --destination="$install_dir/.env_yjs"
chmod 400 "$install_dir/.env_yjs"
chown "$app:$app" "$install_dir/.env_yjs"


#=================================================
# RESTORE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/$app.service"
ynh_restore "/etc/systemd/system/$app-yprovider.service"
ynh_restore "/etc/systemd/system/$app-celery.service"
systemctl enable "$app.service" --quiet
systemctl enable "$app-yprovider.service" --quiet
systemctl enable "$app-celery.service" --quiet

yunohost service add "$app" --description="Simple collaborative notetaking" --log="/var/log/$app/$app.log"
yunohost service add "$app-yprovider" --description="Yprovider for Docs" --log="/var/log/$app/$app-yprovider.log"
yunohost service add "$app-celery" --description="Celery for Docs" --log="/var/log/$app/$app-celery.log"

ynh_restore "/etc/logrotate.d/$app"

#=================================================
# RESTORE VARIOUS FILES
#=================================================

ynh_restore "/var/log/$app/"

#=================================================
# SETUP DEX FOR OIDC
#=================================================
setup_dex

#=================================================
# RELOAD NGINX AND THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

### Typically you only have either $app or PHP-FPM but not both at the same time...
ynh_systemctl --service="$app" --action="start"
ynh_systemctl --service="$app-yprovider" --action="start"
ynh_systemctl --service="$app-celery" --action="start"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
